export const SUBJECTS = [
  {
    id: 1,
    name: 'Arte',
    teacher: 10,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 2,
    name: 'Cultura',
    teacher: 10,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 3,
    name: 'Agronomía',
    teacher: 20,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 4,
    name: 'Física',
    teacher: 30,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 5,
    name: 'Matemáticas',
    teacher: 30,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 6,
    name: 'Estadística',
    teacher: 20,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 7,
    name: 'Filosofía',
    teacher: 40,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 8,
    name: 'Sociología',
    teacher: 50,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 9,
    name: 'Política',
    teacher: 50,
    credits: 3,
    disabled: false,
    selected: false,
  },
  {
    id: 10,
    name: 'Historia',
    teacher: 40,
    credits: 3,
    disabled: false,
    selected: false,
  },
];
